### ISSUE TITLE
Broken tests due to new numpy version

### ISSUE THREAD

**Issue by mfschubert** [facebookresearch/fmmax#122]
Some tests depend upon autograd-backed grcwa, which have started failing due to changes in numpy. It seems autograd will not be updated to address the issue. https://github.com/HIPS/autograd/pull/618

We should perhaps set up CI so that autograd-dependent tests run using a pinned version of numpy.

**Comment by agriyakhetarpal** [comment]
Hi there, we released a new version of Autograd: https://github.com/HIPS/autograd/releases/tag/v1.7.0, which includes NumPy v2 support. It will be available via PyPI later in the day.
