### ISSUE TITLE
Absorbing boundary layer

### ISSUE THREAD

**Issue by mfschubert** [facebookresearch/fmmax#27]
It would be nice to support x/y absorbing boundary conditions, so that non-periodic structures could be modeled.

Unfortunately, this seems to be a bit involved, since u-PML would require magnetic, anisotropic materials. The implementation could be relatively straightforward for the basic "FFT" formulation of the FMM, but it would be good to make this available also for the vector formulations.

If this were implemented, there would also be an opportunity to simplify the layer eigensolve code, which currently has several different functions to handle e.g. uniform, patterned, isotropic, anisotropic cases.

**Comment by smartalecH** [comment]
We should be able to add scalar absorbing boundary layers without too much hassle, right? They won't converge as quickly as PML (which will require larger domains and consequently more Fourier orders) but they seem like a quick and dirty solution.

**Comment by smartalecH** [comment]
(might be good to replace "boundary condition" with "boundary layer" to avoid ambiguity)

**Comment by mfschubert** [comment]
> We should be able to add scalar absorbing boundary layers without too much hassle, right? They won't converge as quickly as PML (which will require larger domains and consequently more Fourier orders) but they seem like a quick and dirty solution.

Yes, that would be a viable alternative. There would be no changes to the core code in this case, it would just be a matter of providing a permittivity array that includes the absorbing material.

**Comment by smartalecH** [comment]
> There would be no changes to the core code in this case, it would just be a matter of providing a permittivity array that includes the absorbing material.

Cool. It might still be worth it to provide an API so the user doesn't have to worry about this. Specifically, we can create a function like
```python
def pad_with_conductivity(length, strength):
    # does the hard stuff
```
which takes care of the appropriate padding and scaling etc.

**Comment by mfschubert** [comment]
This has been addressed by https://github.com/facebookresearch/fmmax/pull/29
