### ISSUE TITLE
Automated releases with new versions

### ISSUE THREAD

**Issue by smartalecH** [facebookresearch/fmmax#45]

**Comment by mfschubert** [comment]
We now have a workflow that does automatic releases, but something may be wrong with the repo secrets:

![image](https://github.com/facebookresearch/fmmax/assets/30735893/b3817b94-d72c-479e-8f5d-1c827bfe1c8a)

**Comment by smartalecH** [comment]
Hmm ok we can generate new secrets if the current ones are dead.

**Comment by mfschubert** [comment]
This seems to be working now, with no changes (?) as evidenced by this successful action:

https://github.com/facebookresearch/fmmax/actions/runs/8484850321
