### ISSUE TITLE
LatticeVector shape checking

### ISSUE THREAD

**Issue by smartalecH** [facebookresearch/fmmax#47]
There is currently a check within `basis.py` to ensure that the `LatticeVectors` are of the proper shape: 

https://github.com/facebookresearch/fmmax/blob/1bc96735251f53e7778590f22520a8049ac6d9d3/fmmax/basis.py#L37-L43

This works fine for simple problems. But when trying to backpropagate through [more complicated structures](https://github.com/google/jax/discussions/18173), jax will expand the shape of the basis accordingly (and this check fails).

Is there a better way to account for this?

(cc @mfschubert )

**Comment by mfschubert** [comment]
I suppose we could just check that the trailing dimension is size 2, rather than that the vectors actually have shape (2,). I don't foresee any issues with that, and iiuc it would enable the use case you have in mind.

**Comment by mfschubert** [comment]
@smartalecH Are you planning on tackling this? If so, it would also be great to add a test for whatever use case you have in mind, e.g. jacobian calculation. I think it might be easy for e.g. changes to the vector module to break this again.

**Comment by smartalecH** [comment]
Yep I'm hoping to get to this sometime this week.
